name: Clash

on:
  schedule:
    - cron: "0 0 * * 1"
  # watch:
  #   types: started
  workflow_dispatch: # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout actions
      uses: actions/checkout@v1

    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'

    - name: run
      run: |
        ls
        pip install requests
        python clash.py
    
    - name: commit
      run: |
        git config --global user.email ${{ secrets.EMAIL }}
        git config --global user.name Fwindy
        git add .
        git commit -m "update" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
